name: Release extension

on:
  workflow_dispatch:

jobs:
  release-extension:
    runs-on: ubuntu-20.04
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install dependencies
      run: npm install
    #- name: Build & package extension for Chrome
    #  run: npm run dist
    #- name: Release extension for Chrome
    #  run: echo "TODO"
    #- name: Build & package extension for Firefox
    #  run: npm run dist-ff
    #- name: Release extension for Firefox
    #  run: echo "TODO"
    - name: Get release version
      run: echo "RELEASE_VERSION=$(npm run --silent get-version)" >> $GITHUB_ENV
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ env.RELEASE_VERSION }}
        body_path: RELEASE_CHANGELOG.md
